import type { Metadata } from "next";
import "./globals.css";
import { Providers } from "@/provider";
import { Poppins } from 'next/font/google';

const poppins = Poppins({
  weight: ['400', '500', '600', '700'],
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: "ConstiPlay",
  description: "Generated by Team Rashtriya Rangers",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Providers>
        <body className={`${poppins.className} antialiased`} >
          {children}
        </body>
      </Providers>
    </html>
  );
}
